from engine import Space, WHITE, RED

ALL_ROLLS = [[1, 1],
[1, 2],
[1, 3],
[1, 4],
[1, 5],
[1, 6],
[2, 1],
[2, 2],
[2, 3],
[2, 4],
[2, 5],
[2, 6],
[3, 1],
[3, 2],
[3, 3],
[3, 4],
[3, 5],
[3, 6],
[4, 1],
[4, 2],
[4, 3],
[4, 4],
[4, 5],
[4, 6],
[5, 1],
[5, 2],
[5, 3],
[5, 4],
[5, 5],
[5, 6],
[6, 1],
[6, 2],
[6, 3],
[6, 4],
[6, 5],
[6, 6]]


STARTING_BOARD = [Space(0, 'bearoff_zone', RED),
                  Space(0, 'bar', WHITE),
                  Space(1, 'outer', WHITE, 2),
                  Space(2, 'outer'),
                  Space(3, 'outer'),
                  Space(4, 'outer'),
                  Space(5, 'outer'),
                  Space(6, 'outer', RED, 5),
                  Space(7, 'outer'),
                  Space(8, 'outer', RED, 3),
                  Space(9, 'outer'),
                  Space(10, 'outer'),
                  Space(11, 'outer'),
                  Space(12, 'outer', WHITE, 5),
                  Space(13, 'outer', RED, 5),
                  Space(14, 'outer'),
                  Space(15, 'outer'),
                  Space(16, 'outer'),
                  Space(17, 'outer', WHITE, 3),
                  Space(18, 'outer'),
                  Space(19, 'outer', WHITE, 5),
                  Space(20, 'outer'),
                  Space(21, 'outer'),
                  Space(22, 'outer'),
                  Space(23, 'outer'),
                  Space(24, 'outer', RED, 2),
                  Space(25, 'bearoff_zone', WHITE),
                  Space(25, 'bar', RED)
                  ]

TEST_ONE_ON_BAR = [Space(0, 'bearoff_zone', RED),
                  Space(0, 'bar', WHITE),
                  Space(1, 'outer', RED, 12),
                  Space(2, 'outer'),
                  Space(3, 'outer'),
                  Space(4, 'outer'),
                  Space(5, 'outer', RED, 1),
                  Space(6, 'outer', RED, 1),
                  Space(7, 'outer'),
                  Space(8, 'outer'),
                  Space(9, 'outer'),
                  Space(10, 'outer'),
                  Space(11, 'outer'),
                  Space(12, 'outer'),
                  Space(13, 'outer'),
                  Space(14, 'outer'),
                  Space(15, 'outer'),
                  Space(16, 'outer'),
                  Space(17, 'outer'),
                  Space(18, 'outer'),
                  Space(19, 'outer', WHITE, 5),
                  Space(20, 'outer', WHITE, 5),
                  Space(21, 'outer'),
                  Space(22, 'outer', WHITE, 2),
                  Space(23, 'outer', WHITE, 3),
                  Space(24, 'outer'),
                  Space(25, 'bearoff_zone', WHITE),
                  Space(25, 'bar', RED, 1)
                  ]

TEST_TWO_ON_BAR = [Space(0, 'bearoff_zone', RED),
                  Space(0, 'bar', WHITE),
                  Space(1, 'outer', RED, 11),
                  Space(2, 'outer'),
                  Space(3, 'outer'),
                  Space(4, 'outer'),
                  Space(5, 'outer', RED, 1),
                  Space(6, 'outer', RED, 1),
                  Space(7, 'outer'),
                  Space(8, 'outer'),
                  Space(9, 'outer'),
                  Space(10, 'outer'),
                  Space(11, 'outer'),
                  Space(12, 'outer'),
                  Space(13, 'outer'),
                  Space(14, 'outer'),
                  Space(15, 'outer'),
                  Space(16, 'outer'),
                  Space(17, 'outer'),
                  Space(18, 'outer'),
                  Space(19, 'outer', WHITE, 5),
                  Space(20, 'outer', WHITE, 5),
                  Space(21, 'outer'),
                  Space(22, 'outer', WHITE, 2),
                  Space(23, 'outer', WHITE, 3),
                  Space(24, 'outer'),
                  Space(25, 'bearoff_zone', WHITE),
                  Space(25, 'bar', RED, 2)
                  ]


TEST_LARGESE_MOVE = [Space(0, 'bearoff_zone', RED),
                  Space(0, 'bar', WHITE),
                  Space(1, 'outer', RED, 12),
                  Space(2, 'outer'),
                  Space(3, 'outer', RED, 2),
                  Space(4, 'outer'),
                  Space(5, 'outer'),
                  Space(6, 'outer'),
                  Space(7, 'outer'),
                  Space(8, 'outer'),
                  Space(9, 'outer'),
                  Space(10, 'outer'),
                  Space(11, 'outer'),
                  Space(12, 'outer', WHITE, 5),
                  Space(13, 'outer'),
                  Space(14, 'outer'),
                  Space(15, 'outer'),
                  Space(16, 'outer'),
                  Space(17, 'outer'),
                  Space(18, 'outer'),
                  Space(19, 'outer', WHITE, 5),
                  Space(20, 'outer', WHITE, 5),
                  Space(21, 'outer', RED, 1),
                  Space(22, 'outer'),
                  Space(23, 'outer'),
                  Space(24, 'outer'),
                  Space(25, 'bearoff_zone', WHITE),
                  Space(25, 'bar', RED)
                  ]


TEST_DOUBLES = [Space(0, 'bearoff_zone', RED),
                  Space(0, 'bar', WHITE),
                  Space(1, 'outer', RED, 12),
                  Space(2, 'outer'),
                  Space(3, 'outer', RED, 2),
                  Space(4, 'outer'),
                  Space(5, 'outer'),
                  Space(6, 'outer'),
                  Space(7, 'outer'),
                  Space(8, 'outer'),
                  Space(9, 'outer'),
                  Space(10, 'outer'),
                  Space(11, 'outer'),
                  Space(12, 'outer'),
                  Space(13, 'outer', WHITE, 5),
                  Space(14, 'outer'),
                  Space(15, 'outer'),
                  Space(16, 'outer'),
                  Space(17, 'outer'),
                  Space(18, 'outer'),
                  Space(19, 'outer', WHITE, 5),
                  Space(20, 'outer', WHITE, 5),
                  Space(21, 'outer', RED, 1),
                  Space(22, 'outer'),
                  Space(23, 'outer'),
                  Space(24, 'outer'),
                  Space(25, 'bearoff_zone', WHITE),
                  Space(25, 'bar', RED)
                  ]


TEST_NO_LEGAL_MOVES_BAR = [Space(0, 'bearoff_zone', RED),
                  Space(0, 'bar', WHITE, 1),
                  Space(1, 'outer'),
                  Space(2, 'outer', RED, 2),
                  Space(3, 'outer', RED, 2),
                  Space(4, 'outer', RED, 2),
                  Space(5, 'outer', RED, 2),
                  Space(6, 'outer', RED, 2),
                  Space(7, 'outer', RED, 5),
                  Space(8, 'outer'),
                  Space(9, 'outer'),
                  Space(10, 'outer'),
                  Space(11, 'outer'),
                  Space(12, 'outer'),
                  Space(13, 'outer', WHITE, 14),
                  Space(14, 'outer'),
                  Space(15, 'outer'),
                  Space(16, 'outer'),
                  Space(17, 'outer'),
                  Space(18, 'outer'),
                  Space(19, 'outer'),
                  Space(20, 'outer'),
                  Space(21, 'outer'),
                  Space(22, 'outer'),
                  Space(23, 'outer'),
                  Space(24, 'outer'),
                  Space(25, 'bearoff_zone', WHITE),
                  Space(25, 'bar', RED)
                  ]

TEST_NO_LEGAL_MOVES_BLOCKED =  [Space(0, 'bearoff_zone', RED),
                  Space(0, 'bar', WHITE),
                  Space(1, 'outer', WHITE, 15),
                  Space(2, 'outer', RED, 15),
                  Space(3, 'outer'),
                  Space(4, 'outer'),
                  Space(5, 'outer'),
                  Space(6, 'outer'),
                  Space(7, 'outer'),
                  Space(8, 'outer'),
                  Space(9, 'outer'),
                  Space(10, 'outer'),
                  Space(11, 'outer'),
                  Space(12, 'outer'),
                  Space(13, 'outer'),
                  Space(14, 'outer'),
                  Space(15, 'outer'),
                  Space(16, 'outer'),
                  Space(17, 'outer'),
                  Space(18, 'outer'),
                  Space(19, 'outer'),
                  Space(20, 'outer'),
                  Space(21, 'outer'),
                  Space(22, 'outer'),
                  Space(23, 'outer'),
                  Space(24, 'outer'),
                  Space(25, 'bearoff_zone', WHITE),
                  Space(25, 'bar', RED)
                  ]
